### PR TITLE
Spelling corrections

### PR DESCRIPTION
**Pull request by kartiklunkad26**
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Thanks for submitting a pull request!

All pull request submitters and commit authors must have a Contributor License Agreement (CLA) on-file with us. Please sign the appropriate CLA ([individual](http://cloudfoundry.org/pdfs/CFF_Individual_CLA.pdf) or [corporate](http://cloudfoundry.org/pdfs/CFF_Corporate_CLA.pdf)).

When sending signed CLA please provide your github username in case of individual CLA or the list of github usernames that can make pull requests on behalf of your organization.

If you are confident that you're covered under a Corporate CLA, please make sure you've publicized your membership in the appropriate Github Org, per [these instructions](https://help.github.com/articles/publicizing-or-concealing-organization-membership/).

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

No need to run unit tests.

### CODE REVIEW

**Comment by bingosummer** [comment]
Thanks @kartiklunkad26 for your contribution.
Please sign the appropriate CLA, close the PR and re-open it.

**Comment by bingosummer** [comment]
@kartiklunkad26 , a CLA is required by Cloud Foundry Foundation. The PR can't be merged unless you sign the CLA.

**Comment by bingosummer** [comment]
@kartiklunkad26 
Since the CLA is not signed, I will close the PR. I will submit a separated PR to include your change.
Please feel free to contribute more PRs after you sign the CLA. :)

**Comment by kartiklunkad26** [comment]
Apologies for not responding here. Realized my notifications on Github weren't redirected properly to my email. Thanks for incorporating the change! :)

**Pull request closed without merging**
